server:
  servlet:
    context-path: /spring-boot-admin/v1
  error:
    include-binding-errors: always
    include-message: always
management:
  security:
    enabled: false
management.endpoints.web.exposure.include: "health,info,prometheus"
management.endpoints.health.show-details: always
management.endpoints.health.probes.enabled: true

spring:
  application:
    name: spring-boot-submodule
  main:
    allow-bean-definition-overriding: true
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto:none
    properties:
      hibernate:
        generate_statistics: true
        jdbc.fetch_size: 100
        jdbc.batch_size: 100
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        query.in_clause_parameter_padding: true
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password: Unicoin123
    driverClassName: com.mysql.cj.jdbc.Driver
